### PR TITLE
Ability to export env

### PR DESCRIPTION
**Pull request by ManojKiranA**
As the heading says i have added option to export the env to file.

Meanwhile i don't have knowledge about css so sorry for the button alignment.

https://user-images.githubusercontent.com/30294553/104031088-4f577800-51f2-11eb-85d8-cf73df8bee3e.mp4

### CODE REVIEW

**Comment by ManojKiranA** [comment]
I am not sure how to test for file downloads. 😢

**Comment by danharrin** [comment]
Hey, thanks for your work on this! I'm gonna hold off merging it for a little while until #35 gets more support from the community, I'm conscious that adding too many features to the dashboard will clutter it so I want to make sure that other people think its a valuable addition. Many thanks again!

**Comment by dsone** [comment]
I'd say that is definitely a missing feature. Especially for a lot of variables this can come in handy.

However, if the position is the same as in the screen recording, I'd favor a reposition of the button to be like the "Manage App" button: 
To the right and only under the header if the screen size is too small (with a bit more margin on top as is in the video). 
Additionally, perhaps with a different, more subtle color or it really does feel cluttered as Dan mentions because that blueish color is very aggressive.

If it is white like the "Import" it's subtle enough, imo
image

**Comment by danharrin** [comment]
Fancy PRing the design tweak with the white button?

**Comment by danharrin** [comment]
Closing in favour of #43.

**Pull request closed without merging**
